# Generated by Django 2.2 on 2019-04-16 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0001_initial'),
    ]

    operations = [
    ]
