# Generated by Django 2.2 on 2019-04-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0002_auto_20190416_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'verbose_name': '工作日程', 'verbose_name_plural': '工作日程'},
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='content',
            field=models.TextField(verbose_name='工作日程'),
        ),
    ]
